services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      SERVICE_NAME: api
      LOG_INTERVAL_SECONDS: "0.4"
      ERROR_PROBABILITY: "0.15"
      EXCEPTION_PROBABILITY: "0.05"
      TIMEOUT_PROBABILITY: "0.05"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    environment:
      SERVICE_NAME: worker
      LOG_INTERVAL_SECONDS: "0.6"
      ERROR_PROBABILITY: "0.10"
      EXCEPTION_PROBABILITY: "0.03"
      TIMEOUT_PROBABILITY: "0.04"
