services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    environment:
      SERVICE_NAME: api
      LOG_INTERVAL_SECONDS: "0.4"
      ALERT_EVERY_SECONDS: "20"
      ALLOW_RANDOM_ALERTS: "0"
      ERROR_PROBABILITY: "0"
      EXCEPTION_PROBABILITY: "0"
      TIMEOUT_PROBABILITY: "0"

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: worker
    environment:
      SERVICE_NAME: worker
      LOG_INTERVAL_SECONDS: "0.6"
      ALERT_EVERY_SECONDS: "20"
      ALLOW_RANDOM_ALERTS: "0"
      ERROR_PROBABILITY: "0"
      EXCEPTION_PROBABILITY: "0"
      TIMEOUT_PROBABILITY: "0"
